#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# i.MX 95 U-Boot interactive-prompt regression.
#
# A lean, network-free CI guard that the SD/eMMC boot chain reaches a *live,
# interactive* U-Boot prompt:
#
#   ROM handover + passover tables
#     -> SM boots on the M33, brings up SCMI, releases the A55 from CPUWAIT
#     -> SPL walks image set 0 and loads U-Boot proper from the next container
#     -> U-Boot proper reaches its prompt, and executes commands we type
#
# tests/uboot/run.sh already exercises this chain, but it also drives the ENETC
# TFTP datapath and depends on the network model; this test isolates just the
# "does the interactive prompt work" question so a prompt regression is caught
# on its own, cheaply, with no networking.
#
# PASS = SPL banner + U-Boot proper + the "u-boot=>" prompt + a unique string we
#        `echo` AT the prompt comes back (proving the prompt ran our command),
#        with no boot anomalies.
#
# Boot media is generated by tests/uboot/mkbootimg.py (no imx-mkimage needed).
# Required (override via env): QEMU, SM_ELF, SPL_BIN, UBOOT_BIN. Skips cleanly
# if any is absent.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd); ROOT=$(cd "$HERE/../.." && pwd)
QEMU=${QEMU:-$ROOT/build/qemu-system-aarch64}
SM_ELF=${SM_ELF:-${SMELF:-$HOME/Documents/nxp/sources/imx-sm/build/mx95evk/m33_image.elf}}
SPL_BIN=${SPL_BIN:-$ROOT/tests/spl-banner/uboot-build/spl/u-boot-spl.bin}
UBOOT_BIN=${UBOOT_BIN:-$ROOT/tests/spl-banner/uboot-build/u-boot.bin}
MKBOOTIMG=$ROOT/tests/uboot/mkbootimg.py
TMO=${TMO:-180}

skip() { echo "SKIP: $*"; exit 0; }
need() { [ -e "$2" ] || skip "missing $1: $2"; }
need QEMU "$QEMU"; need SM_ELF "$SM_ELF"
need SPL_BIN "$SPL_BIN"; need UBOOT_BIN "$UBOOT_BIN"
need mkbootimg "$MKBOOTIMG"

WORK=$(mktemp -d); trap 'rm -rf "$WORK"' EXIT
LOG=${LOG:-$WORK/serial.log}
MARK="UBOOT_PROMPT_OK_$$"          # unique per run; only appears if a typed cmd ran

python3 "$MKBOOTIMG" "$UBOOT_BIN" "$WORK/boot.img" >/dev/null

# Hammer newlines to interrupt autoboot, then type a few benign commands. The
# `echo $MARK` is the interactivity witness: it can only appear in the log if the
# prompt actually executed the line we sent.
{
    for _ in $(seq 1 30); do printf '\n'; sleep 0.25; done
    sleep 2
    printf 'version\n';                 sleep 2
    printf 'printenv baudrate\n';       sleep 2
    printf 'md.l 0x90000000 2\n';       sleep 2
    printf 'echo %s\n' "$MARK";         sleep 2
} | timeout -k 5 "$TMO" "$QEMU" -M imx95-19x19-evk -m 2G -display none \
    -device loader,file="$SPL_BIN",addr=0x20480000,cpu-num=0,force-raw=on \
    -device loader,file="$SM_ELF",cpu-num=6 \
    -drive if=none,format=raw,file="$WORK/boot.img",id=mmc0 -device emmc,drive=mmc0 \
    -serial stdio -serial null 2>&1 | sed 's/\x1b\[[0-9;]*[a-zA-Z]//g' > "$LOG" || true

echo "=== u-boot prompt report ==="
grep -aE "^U-Boot SPL|Trying to boot from|^U-Boot 20|u-boot=>|baudrate=|$MARK" "$LOG" | head -12

pass=1
grep -qa 'U-Boot SPL'  "$LOG" && echo "  ok   SPL banner"       || { echo "  MISS SPL banner"; pass=0; }
grep -qaE '^U-Boot 20' "$LOG" && echo "  ok   U-Boot proper"    || { echo "  MISS U-Boot proper"; pass=0; }
grep -qa 'u-boot=>'    "$LOG" && echo "  ok   prompt present"   || { echo "  MISS prompt"; pass=0; }
grep -qa "$MARK"       "$LOG" && echo "  ok   prompt is interactive (typed command ran)" \
                              || { echo "  MISS interactive echo ($MARK)"; pass=0; }
grep -qa 'baudrate='   "$LOG" && echo "  ok   env readable (printenv baudrate)" \
                              || { echo "  MISS printenv output"; pass=0; }
for a in 'Kernel panic' 'Synchronous Abort' 'Unhandled fault' 'ERROR ### Please RESET' 'resetting'; do
    grep -qa "$a" "$LOG" && { echo "  MISS anomaly: $a"; pass=0; }
done

[ "$pass" = 1 ] && { echo "PASS: U-Boot SD-boot chain reaches an interactive prompt"; exit 0; }
echo "FAIL"; exit 1
