#!/usr/bin/env bash
#
# Wire an operator-supplied eIQ Neutron SDK into the QEMU i.MX 95 runner backend.
#
# This script COPIES NOTHING from the SDK. It records the PATH to the user's own
# `neutron-runner` (which the user downloaded from NXP under their own eIQ SDK
# LA_OPT license) into a local, gitignored env file. Our repository never
# contains any NXP-licensed content; the SDK stays where the user extracted it.
#
# See docs/neutron-runner-operator-supplies.md.
#
# Usage:
#   scripts/neutron-runner-setup.sh --sdk <extracted eIQ Neutron SDK dir> \
#       [--out build/neutron-runner.local.env] \
#       [--fixtures hw/misc/imx95_neutron_fixtures.mobilenet_v1.json]
#
# SPDX-License-Identifier: GPL-2.0-or-later
set -euo pipefail

SDK=""
OUT="build/neutron-runner.local.env"
FIXTURES="hw/misc/imx95_neutron_fixtures.mobilenet_v1.json"

while [ $# -gt 0 ]; do
    case "$1" in
        --sdk)      SDK="${2:-}"; shift 2 ;;
        --out)      OUT="${2:-}"; shift 2 ;;
        --fixtures) FIXTURES="${2:-}"; shift 2 ;;
        -h|--help)
            sed -n '2,20p' "$0"; exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

if [ -z "$SDK" ]; then
    echo "usage: $0 --sdk <extracted eIQ Neutron SDK dir>" >&2
    exit 2
fi

RUNNER="$SDK/bin/neutron-runner"
if [ ! -x "$RUNNER" ]; then
    echo "ERROR: no executable neutron-runner at: $RUNNER" >&2
    echo >&2
    echo "  Download the eIQ Neutron SDK from NXP (eiq.nxp.com), accept the" >&2
    echo "  license, extract it, and pass its top-level directory with --sdk." >&2
    echo "  This script copies NOTHING from the SDK - it only records the path." >&2
    exit 1
fi

REPO="$(git rev-parse --show-toplevel)"

# Refuse to proceed if the SDK sits INSIDE the repo checkout: that is the one
# way an NXP-licensed file could ever be staged/committed. Keep it outside.
SDK_ABS="$(cd "$SDK" && pwd -P)"
case "$SDK_ABS/" in
    "$REPO"/*)
        echo "ERROR: the SDK is inside the repo checkout:" >&2
        echo "         $SDK_ABS" >&2
        echo "       Move it OUTSIDE $REPO so no NXP-licensed file can ever be" >&2
        echo "       staged or committed. Then re-run with the new --sdk path." >&2
        exit 1 ;;
esac

if [ ! -f "$REPO/$FIXTURES" ]; then
    echo "ERROR: fixtures map not found: $REPO/$FIXTURES" >&2
    exit 1
fi

# Informational only. Per LA_OPT 3.8, do NOT publish reports (incl. version/perf
# telemetry) from runner use; this line stays in the local, gitignored env file.
VER="$("$RUNNER" --version 2>/dev/null | head -1 || echo unknown)"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# GENERATED by scripts/neutron-runner-setup.sh -- DO NOT COMMIT (gitignored).
# Paths only, no NXP content. The referenced files are the USER's, used under
# the user's own NXP eIQ SDK LA_OPT license. See docs/neutron-runner-*.md.
export NEUTRON_RUNNER_PATH="$RUNNER"
export NEUTRON_RUNNER_SDK="$SDK_ABS"
export NEUTRON_FIXTURES="$REPO/$FIXTURES"
# runner version seen at setup (informational, DO NOT publish -- LA_OPT 3.8): $VER
EOF

echo "Wrote $OUT"
echo "  runner   : $RUNNER"
echo "  fixtures : $REPO/$FIXTURES"
echo
echo "Next:"
echo "  source $OUT"
echo "  # then launch QEMU with the runner backend, e.g.:"
echo "  #   -global driver=imx95.neutron,compute-backend=runner \\"
echo "  #   -global driver=imx95.neutron,neutron-runner-path=\$NEUTRON_RUNNER_PATH \\"
echo "  #   -global driver=imx95.neutron,neutron-runner-fixtures=\$NEUTRON_FIXTURES"
echo
echo "Reminder: do not publish performance reports from runner use (LA_OPT 3.8)."
